### ISSUE TITLE
sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by clarkenj** [SIMEXP/giga_preprocess2#24]
Am getting the following error with cima-q, although using the adapted abide script (scripts [here](https://github.com/SIMEXP/giga_preprocess2/pull/23/commits/d111077145f1a0aa93a47f5abd29e59af1babaae)). I did not put all of the atlas/denoising strategies as wanted to get it running first. One job continues to run fine, so the issue is with multiple ones. Anything I can try @htwangtw?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/bin/giga_connectome", line 8, in <module>
    sys.exit(main())
  File "/code/giga_connectome/run.py", line 111, in main
    workflow(args)
  File "/code/giga_connectome/workflow.py", line 74, in workflow
    subj_data, fmriprep_bids_layout = utils.get_bids_images(
  File "/code/giga_connectome/utils.py", line 21, in get_bids_images
    layout = BIDSLayout(
  File "/usr/local/lib/python3.9/site-packages/bids/layout/layout.py", line 149, in __init__
    self.connection_manager = ConnectionManager(
  File "/usr/local/lib/python3.9/site-packages/bids/layout/db.py", line 45, in __init__
    self.reset_database(init_args, config)
  File "/usr/local/lib/python3.9/site-packages/bids/layout/db.py", line 103, in reset_database
    Base.metadata.drop_all(self.engine)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 4690, in drop_all
    bind._run_visitor(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2095, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1656, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 955, in visit_metadata
    self.traverse_single(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 1018, in visit_table
    self.connection.execute(DropTable(table))
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1068, in _execute_ddl
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL:
DROP TABLE config_to_entity_map]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

**Comment by htwangtw** [comment]
Did you let one job finish running before submitting the full batch? I only run into this if the bids database has not been indexed + multiple jobs are doing that at the same time

I would look into this error message + bids as keywords to understand the full picture a bit more... Or @Remi-Gau might have a better idea quicker than google

On the other hand, I might want to expose the bids database path to users so they can manipulate this for multiple jobs smoothly

**Comment by htwangtw** [comment]
This is the same error but in fmriprep and their solutions: https://github.com/nipreps/fmriprep/issues/2313#issuecomment-1013680975

**Comment by clarkenj** [comment]
I thought I had try that but will run again to make sure. Thank you!

**Comment by clarkenj** [comment]
I still get the error after letting one job finish. Will look into the solutions you shared.

**Comment by clarkenj** [comment]
The solution there seems to be using a home directory for outputs (but particularly the working directory) instead of scratch, but I still get the error, including after letting it finish running one job. I also tried mounting the fmriprep directory to my local machine and running from there, but it was the same. It seems to arise from having multiple processes accessing the bids database at the same time. Some possible solutions I've read about is forcing a single connection per job (which I guess would be v expensive), or implementing a connection pool. I've also asked @Hyedryn for his ukbb script to run the connectomes - Quentin did you come across this problem at all?

**Comment by htwangtw** [comment]
Quick link to UKBB: https://github.com/Hyedryn/ukbb-scripts/blob/dev/9_connectome.py
